#!/usr/bin/env bash
#
# A stand-in for an AI coding agent, driven entirely by shell.
#
#   * NO LLM calls, no network, no API keys.
#   * `clada run` supervises THIS script exactly as it would supervise a real
#     agent such as `claude` or `codex` — same PTY, same JSONL log, same audit
#     report. Swapping in a real agent is just a different argv.
#
# The script performs one legitimate write and two writes CLADA should block,
# so the demo can show enforcement working without any paid API access.
set -u

echo "[agent] starting simulated work session"

# 1. A legitimate edit. This succeeds and is captured as a session-owned
#    change in the audit report's path-scoped rollback plan.
echo "[agent] writing a legitimate artifact -> examples/_demo_artifact.txt"
printf 'generated by the CLADA demo agent\n' > examples/_demo_artifact.txt

# 2. A protected write: tamper with CLADA's own decision record. CLADA hardens
#    docs/decisions/ to read-only (chmod 555) before the agent starts, so this
#    MUST fail on a system where chmod hardening sticks.
echo "[agent] attempting to tamper with a guardrail file -> docs/decisions/DR-000-demo.md"
if printf 'INJECTED BY AGENT\n' >> docs/decisions/DR-000-demo.md 2>/dev/null; then
  echo "[agent] !! tamper SUCCEEDED — protection did not hold (see Known Limitations)"
else
  echo "[agent] -> tamper BLOCKED by CLADA (permission denied)"
fi

# 3. A protected create: drop a brand-new file into the guardrail directory.
echo "[agent] attempting to plant a new file -> docs/decisions/DR-666-rogue.md"
if printf 'rogue\n' > docs/decisions/DR-666-rogue.md 2>/dev/null; then
  echo "[agent] !! create SUCCEEDED — protection did not hold (see Known Limitations)"
else
  echo "[agent] -> create BLOCKED by CLADA (permission denied)"
fi

echo "[agent] done"
